<a href="https://colab.research.google.com/github/lokithasans2/Data-Analytics-using-Python-Project/blob/main/day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
def attendance(attended, total):
  return (attended / total) * 100

attended = int(input("classes attended:"))
total = int(input("total classes:"))

percentage = attendance(attended, total)

print("attendance percentage =", round (percentage, 2), "%")

classes attended:95
total classes:100
attendance percentage = 95.0 %


In [3]:
import numpy as np
arr = np.array([57,78,90,98,12])
print(arr)

[57 78 90 98 12]


In [6]:
import numpy as np
arr = np.array([
    [[1,5],[6,7]],
      [[6,8],[6,9]]
])
print(arr)

[[[1 5]
  [6 7]]

 [[6 8]
  [6 9]]]
